### ISSUE TITLE
Pink game view: Shader error in DeferredAO

### ISSUE THREAD

**Issue by movrajr** [keijiro/DeferredAO#1]
> Shader error in 'Hidden/DeferredAO': unable to unroll loop, loop does not appear to terminate in a timely manner (573 iterations) or unrolled loop is too large, use the [unroll(n)] attribute to force an exact higher number at line 100 (on d3d11)
> 
> Compiling Fragment program with _SAMPLE_LOW
> 
> Shader warning in 'Hidden/DeferredAO': gradient instruction used in a loop with varying iteration, forcing loop to unroll at line 115 (on d3d11)
> 
> Compiling Fragment program with _SAMPLE_LOW

Tested on Win 7 x64, Unity 5.1.1, D3D11 / D3D9 / OpenGL.

**Comment by keijiro** [comment]
Fixed https://github.com/keijiro/DeferredAO/commit/5d63e2f55eea1216cea234e60d38379a699744bb
